package com.github.mslenc.dbktx.sqltypes

import com.github.mslenc.dbktx.util.Sql
import kotlin.reflect.KClass

class SqlTypeLong(
        private val concreteType: SqlTypeKind,
        isNotNull: Boolean,
        isAutoGenerated: Boolean,
        isUnsigned: Boolean)

    : SqlTypeNumeric<Long>(isNotNull = isNotNull,
                           isAutoGenerated = isAutoGenerated,
                           isUnsigned = isUnsigned) {

    init {
        when (concreteType) {
            SqlTypeKind.INT -> {
                // ok
            }

            SqlTypeKind.BIGINT -> if (isUnsigned) {
                throw IllegalArgumentException("Use ULong for unsigned bigint")
            }

            else ->
                throw IllegalArgumentException("Unsupported type $concreteType")
        }
    }

    override fun parseRowDataValue(value: Any): Long {
        if (value is Long)
            return value

        if (value is Number)
            return value.toLong()

        throw IllegalArgumentException("Not a long - $value")
    }

    override fun encodeForJson(value: Long): Any {
        return value
    }

    override fun decodeFromJson(value: Any): Long {
        return parseRowDataValue(value)
    }

    override fun toSql(value: Long, sql: Sql) {
        sql(value)
    }

    override val dummyValue: Long = 51561L

    override val kotlinType: KClass<Long> = Long::class
}