package com.github.mslenc.dbktx.sqltypes

import com.github.mslenc.dbktx.util.Sql
import kotlin.reflect.KClass

abstract class SqlType<T : Any> protected constructor(val isNotNull: Boolean, val isAutoGenerated: Boolean = false) {
    /**
     * Parses the value as returned from DB (see asyncdb type mapping to know what to expect). In addition,
     * if the value is already T, it should be returned unmodified (used internally with dummyValues).
     */
    abstract fun parseRowDataValue(value: Any): T

    /**
     * Returns whether the value is logically null. Default implementation returns true only for
     * the actual SQL null, but in some cases, a 0 or something similar represents the same.
     */
    open fun isNullRowDataValue(value: Any?): Boolean {
        return value == null
    }

    /**
     * Encodes the value for use in JSON. In particular, the value should be a String, a Number or a Boolean.
     */
    abstract fun encodeForJson(value: T): Any

    /**
     * Parses the JSON value encoded with encodeForJson.
     */
    abstract fun decodeFromJson(value: Any): T

    /**
     * A dummy value of the appropriate type. Used internally for various shenanigans.
     */
    internal abstract val dummyValue: T

    /**
     * The class T
     */
    abstract val kotlinType: KClass<T>

    /**
     * Encodes the value into SQL. Should generally do the opposite of parseRowDataValue.
     */
    abstract fun toSql(value: T, sql: Sql)

    /**
     * Encodes a null value into SQL, useful as the opposite of isNullRowDataValue.
     */
    open fun toSqlNull(sql: Sql) {
        sql.raw("NULL")
    }
}

