package com.xs0.dbktx.schema

import com.xs0.dbktx.composite.CompositeId
import com.xs0.dbktx.expr.*
import com.xs0.dbktx.crud.EntityValues
import com.xs0.dbktx.util.Sql

private fun buildFieldTuple(id: CompositeId<*, *>): String {
    val sb = StringBuilder()
    for (i in 1 .. id.numColumns) {
        sb.append(if (i == 1) "(" else ", ")
        sb.append(id.getColumn(i).quotedFieldName)
    }
    return sb.append(")").toString()
}

class MultiColumn<E : DbEntity<E, ID>, ID : CompositeId<E, ID>>(
        private val constructor: (List<Any?>) -> ID,
        private val prototype: ID) : NonNullRowProp<E, ID>, CompositeExpr<E, ID> {

    override val numParts: Int
        get() = prototype.numColumns

    private val fieldTuple by lazy { buildFieldTuple(prototype) }

    override fun toSql(sql: Sql, topLevel: Boolean) {
        sql.raw(fieldTuple)
    }

    override fun makeLiteral(value: ID): Expr<E, ID> {
        return value
    }

    override fun getPart(index: Int): Column<E, *> {
        return prototype.getColumn(index)
    }

    override infix fun eq(value: ID): ExprBoolean<E> {
        return ExprBinary(this, ExprBinary.Op.EQ, value)
    }

    override infix fun neq(value: ID): ExprBoolean<E> {
        return ExprBinary(this, ExprBinary.Op.NEQ, value)
    }

    override infix fun oneOf(values: Set<ID>): ExprBoolean<E> {
        return ExprOneOf.oneOf(this, values.toList())
    }

    override operator fun invoke(row: List<Any?>): ID {
        return constructor(row)
    }

    override val isAutoGenerated: Boolean
        get() = false

    override fun extract(values: EntityValues<E>): ID? {
        val numCols = prototype.tableMetainfo.numColumns

        val row = ArrayList<Any?>(numCols)
        for (i in 0 until numCols)
            row.add(null)

        for (i in 1..numParts) {
            val part = getPart(i)
            val value = part.extract(values) ?: return null
            row[part.indexInRow] = value
        }

        return invoke(row)
    }
}