package com.xs0.dbktx.schema

import com.xs0.dbktx.composite.CompositeId
import com.xs0.dbktx.crud.BoundMultiColumnForSelect
import com.xs0.dbktx.expr.*
import com.xs0.dbktx.crud.EntityValues
import com.xs0.dbktx.crud.TableInQuery
import com.xs0.dbktx.util.Sql

class MultiColumn<E : DbEntity<E, ID>, ID : CompositeId<E, ID>>(
        private val constructor: (List<Any?>) -> ID,
        private val prototype: ID) : NonNullRowProp<E, ID> {

    val numColumns: Int
        get() = prototype.numColumns

    override fun makeLiteral(value: ID): Expr<E, ID> {
        return value
    }

    fun getPart(index: Int): Column<E, *> {
        return prototype.getColumn(index)
    }

    override operator fun invoke(row: List<Any?>): ID {
        return constructor(row)
    }

    override val isAutoGenerated: Boolean
        get() = false

    override fun bindForSelect(tableInQuery: TableInQuery<E>): BoundMultiColumnForSelect<E, ID> {
        return BoundMultiColumnForSelect(this, tableInQuery)
    }

    override fun extract(values: EntityValues<E>): ID? {
        val numCols = prototype.tableMetainfo.numColumns

        val row = ArrayList<Any?>(numCols)
        for (i in 0 until numCols)
            row.add(null)

        for (i in 1..numColumns) {
            val part = getPart(i)
            val value = part.extract(values) ?: return null
            row[part.indexInRow] = value
        }

        return invoke(row)
    }
}