package com.xs0.dbktx

import com.xs0.dbktx.sqltypes.SqlType

interface Column<E: DbEntity<E, *>, T : Any> : RowProp<E, T> {
    val table: DbTable<E, *>
    val fieldName: String
    val sqlType: SqlType<T>
    val indexInRow: Int

    override operator fun invoke(row: List<Any?>): T? {
        val value = row[indexInRow] ?: return null

        return sqlType.fromJson(value)
    }

    override val isAutoGenerated: Boolean
        get() = sqlType.isAutoGenerated

    override fun extract(values: EntityValues<E>): T? {
        return values.get(this)
    }

    override fun toSql(sb: SqlBuilder, topLevel: Boolean) {
        sb.name(this)
    }

    override fun makeLiteral(value: T): Expr<E, T> {
        return Literal(value, sqlType)
    }

    operator fun invoke(entity: E): T?
}

interface NonNullColumn<E: DbEntity<E, *>, T: Any>: Column<E, T>, NonNullRowProp<E, T> {
    override fun invoke(row: List<Any?>): T {
        val value = row[indexInRow] ?: throw IllegalStateException("Null value for NOT NULL column $fieldName")

        return sqlType.fromJson(value)
    }

    override operator fun invoke(entity: E): T
}

interface NullableColumn<E: DbEntity<E, *>, T: Any>: Column<E, T>, NullableRowProp<E, T>


interface OrderedColumn<E: DbEntity<E, *>, T: Comparable<T>>: Column<E, T>, OrderedProp<E, T>
interface NonNullOrderedColumn<E: DbEntity<E, *>, T: Comparable<T>>: OrderedColumn<E, T>, NonNullColumn<E, T>, NonNullOrderedProp<E, T>
interface NullableOrderedColumn<E: DbEntity<E, *>, T: Comparable<T>>: OrderedColumn<E, T>, NullableColumn<E, T>, NullableOrderedProp<E, T>


interface StringColumn<E: DbEntity<E, *>> : OrderedColumn<E, String>, ExprString<E>
interface NonNullStringColumn<E: DbEntity<E, *>> : NonNullOrderedColumn<E, String>, StringColumn<E>
interface NullableStringColumn<E: DbEntity<E, *>> : NullableOrderedColumn<E, String>, StringColumn<E>


open class ColumnImpl<E : DbEntity<E, *>, T: Any>(
        override val table: DbTable<E, *>,
        private val getter: (E) -> T?,
        override val fieldName: String,
        override val sqlType: SqlType<T>,
        override val indexInRow: Int)

    : Column<E, T> {

    override fun invoke(entity: E): T? {
        return getter(entity)
    }
}

class NonNullColumnImpl<E : DbEntity<E, *>, T: Any>(
        table: DbTable<E, *>,
        private val getter: (E) -> T,
        fieldName: String,
        sqlType: SqlType<T>,
        indexInRow: Int)

    : ColumnImpl<E, T>(table, getter, fieldName, sqlType, indexInRow),
      NonNullColumn<E, T> {

    override fun invoke(entity: E): T {
        return getter(entity)
    }
}

class NullableColumnImpl<E : DbEntity<E, *>, T: Any>(
        table: DbTable<E, *>,
        getter: (E) -> T?,
        fieldName: String,
        sqlType: SqlType<T>,
        indexInRow: Int)

    : ColumnImpl<E, T>(table, getter, fieldName, sqlType, indexInRow),
      NullableColumn<E, T>



open class OrderedColumnImpl<E : DbEntity<E, *>, T: Comparable<T>>(
        override val table: DbTable<E, *>,
        private val getter: (E) -> T?,
        override val fieldName: String,
        override val sqlType: SqlType<T>,
        override val indexInRow: Int)

    : OrderedColumn<E, T> {

    override fun invoke(entity: E): T? {
        return getter(entity)
    }
}

class NonNullOrderedColumnImpl<E : DbEntity<E, *>, T: Comparable<T>>(
        table: DbTable<E, *>,
        private val getter: (E) -> T,
        fieldName: String,
        sqlType: SqlType<T>,
        indexInRow: Int)

    : OrderedColumnImpl<E, T>(table, getter, fieldName, sqlType, indexInRow),
        NonNullOrderedColumn<E, T> {

    override fun invoke(entity: E): T {
        return getter(entity)
    }
}

class NullableOrderedColumnImpl<E : DbEntity<E, *>, T: Comparable<T>>(
        table: DbTable<E, *>,
        getter: (E) -> T?,
        fieldName: String,
        sqlType: SqlType<T>,
        indexInRow: Int)

    : OrderedColumnImpl<E, T>(table, getter, fieldName, sqlType, indexInRow),
        NullableOrderedColumn<E, T>




sealed class StringColumnImpl<E : DbEntity<E, *>>(
        override val table: DbTable<E, *>,
        private val getter: (E) -> String?,
        override val fieldName: String,
        override val sqlType: SqlType<String>,
        override val indexInRow: Int)

    : StringColumn<E> {

    override fun invoke(entity: E): String? {
        return getter(entity)
    }
}

class NonNullStringColumnImpl<E : DbEntity<E, *>>(
        table: DbTable<E, *>,
        private val getter: (E) -> String,
        fieldName: String,
        sqlType: SqlType<String>,
        indexInRow: Int)

    : StringColumnImpl<E>(table, getter, fieldName, sqlType, indexInRow),
      NonNullStringColumn<E>
{

    override fun invoke(entity: E): String {
        return getter(entity)
    }
}

class NullableStringColumnImpl<E : DbEntity<E, *>>(
        table: DbTable<E, *>,
        getter: (E) -> String?,
        fieldName: String,
        sqlType: SqlType<String>,
        indexInRow: Int)
    : StringColumnImpl<E>(table, getter, fieldName, sqlType, indexInRow),
      NullableStringColumn<E>

