package com.xs0.dbktx.sqltypes

import com.xs0.dbktx.util.SqlBuilder
import java.math.BigDecimal
import kotlin.reflect.KClass

class SqlTypeBigDecimal(concreteType: SqlTypeKind,
                        val precision: Int,
                        val scale: Int,
                        isNotNull: Boolean,
                        isUnsigned: Boolean)
    : SqlTypeNumeric<BigDecimal>(isNotNull = isNotNull, isAutoGenerated = false, isUnsigned = isUnsigned) {

    init {
        if (concreteType != SqlTypeKind.DECIMAL)
            throw IllegalArgumentException("Unsupported type " + concreteType)

        if (precision !in 1..65)
            throw IllegalArgumentException("Invalid precision")
        if (scale !in 0..minOf(30, precision))
            throw IllegalArgumentException("Invalid scale")
    }

    override fun fromJson(value: Any): BigDecimal {
        if (value is CharSequence)
            return BigDecimal(value.toString())

        throw IllegalArgumentException("Not a string(bigdecimal) value - " + value)
    }

    override fun toJson(value: BigDecimal): String {
        return value.toString()
    }

    override fun dummyValue(): BigDecimal {
        return BigDecimal.ONE
    }

    override fun toSql(value: BigDecimal, sb: SqlBuilder, topLevel: Boolean) {
        sb.sql("?").param(value.toString())
    }

    override val kotlinType: KClass<BigDecimal> = BigDecimal::class
}
