package com.xs0.dbktx.sqltypes

import com.xs0.dbktx.FieldProps
import com.xs0.dbktx.Sqlable
import kotlin.reflect.KClass

abstract class SqlType<T : Any> protected constructor(props: FieldProps) : Sqlable<T> {
    val isNotNull: Boolean = props.isNotNull
    val isAutoGenerated: Boolean = props.isAutoIncrement

    abstract fun fromJson(value: Any): T

    abstract fun toJson(value: T): Any

    abstract fun dummyValue(): T

    abstract val kotlinType: KClass<T>
}

enum class SqlTypeKind {
    BIT,
    TINYINT,
    BOOLEAN,
    SMALLINT,
    MEDIUMINT,
    INT,
    BIGINT,
    DECIMAL,
    FLOAT,
    DOUBLE,

    DATE,
    DATETIME,
    TIMESTAMP,
    TIME,
    YEAR,

    CHAR,
    VARCHAR,
    TINYTEXT,
    TEXT,
    MEDIUMTEXT,
    LONGTEXT,

    BINARY,
    VARBINARY,
    TINYBLOB,
    BLOB,
    MEDIUMBLOB,
    LONGBLOB,

    ENUM,
    SET
}