package com.xs0.dbktx.sqltypes

abstract class SqlTypeNumeric<T : Any> protected constructor(
        isNotNull: Boolean,
        isAutoGenerated: Boolean,
        val isUnsigned: Boolean) : SqlType<T>(isNotNull, isAutoGenerated)
