package com.xs0.dbktx.sqltypes

import com.xs0.dbktx.SqlBuilder
import kotlin.reflect.KClass

abstract class SqlType<T : Any> protected constructor(val isNotNull: Boolean, val isAutoGenerated: Boolean = false) {
    abstract fun fromJson(value: Any): T
    abstract fun toJson(value: T): Any
    abstract fun dummyValue(): T
    abstract val kotlinType: KClass<T>
    abstract fun toSql(partA: T, sb: SqlBuilder, topLevel: Boolean)
}

enum class SqlTypeKind {
    BIT,
    TINYINT,
    BOOLEAN,
    SMALLINT,
    MEDIUMINT,
    INT,
    BIGINT,
    DECIMAL,
    FLOAT,
    DOUBLE,

    DATE,
    DATETIME,
    TIMESTAMP,
    TIME,
    YEAR,

    CHAR,
    VARCHAR,
    TINYTEXT,
    TEXT,
    MEDIUMTEXT,
    LONGTEXT,

    BINARY,
    VARBINARY,
    TINYBLOB,
    BLOB,
    MEDIUMBLOB,
    LONGBLOB,

    ENUM,
    SET
}