package com.xs0.dbktx.sqltypes

import com.xs0.dbktx.util.Sql
import kotlin.reflect.KClass

class SqlTypeInt(concreteType: SqlTypeKind, isNotNull: Boolean, isAutoGenerated: Boolean, isUnsigned: Boolean) : SqlTypeNumeric<Int>(isNotNull, isAutoGenerated, isUnsigned) {
    private val minVal: Int
    private val maxVal: Int

    init {
        when (concreteType) {
            SqlTypeKind.TINYINT -> if (isUnsigned) {
                this.minVal = 0
                this.maxVal = 255
            } else {
                this.minVal = java.lang.Byte.MIN_VALUE.toInt()
                this.maxVal = java.lang.Byte.MAX_VALUE.toInt()
            }

            SqlTypeKind.SMALLINT -> if (isUnsigned) {
                this.minVal = 0
                this.maxVal = 65535
            } else {
                this.minVal = java.lang.Short.MIN_VALUE.toInt()
                this.maxVal = java.lang.Short.MAX_VALUE.toInt()
            }

            SqlTypeKind.MEDIUMINT -> if (isUnsigned) {
                this.minVal = 0
                this.maxVal = 16777215
            } else {
                this.minVal = -8388608
                this.maxVal = 8388607
            }

            SqlTypeKind.INT -> {
                if (isUnsigned) {
                    throw IllegalArgumentException("INT UNSIGNED must be a Long")
                }

                this.minVal = Integer.MIN_VALUE
                this.maxVal = Integer.MAX_VALUE
            }

            else -> throw IllegalArgumentException("Unsupported type $concreteType")
        }
    }

    override fun parseRowDataValue(value: Any): Int {
        if (value is Int)
            return value

        if (value is Number)
            return value.toInt()

        throw IllegalArgumentException("Not an int - $value")
    }

    override fun encodeForJson(value: Int): Any {
        return value
    }

    override fun decodeFromJson(value: Any): Int {
        return parseRowDataValue(value)
    }

    override fun toSql(value: Int, sql: Sql) {
        sql(value)
    }

    override val dummyValue: Int = maxVal / 2

    override val kotlinType: KClass<Int> = Int::class
}
